### ISSUE TITLE
Incorrect document title 

### ISSUE THREAD

**Issue by aerospace666** [CongHien/SWE-Atrax#15]
![incorrect_title](https://user-images.githubusercontent.com/20936731/46010365-b1fdd600-c105-11e8-84bc-9ce7ed809018.PNG)
![expected_title](https://user-images.githubusercontent.com/20936731/46010374-bde99800-c105-11e8-8943-d998e31ad9e7.PNG)

**Comment by CongHien** [comment]
added editable label
