### ISSUE TITLE
TFIDF failed to generate keywords for some files

### ISSUE THREAD

**Issue by CongHien** [CongHien/SWE-Atrax#26]
<img width="1440" alt="screen shot 2018-10-10 at 10 27 45 am" src="https://user-images.githubusercontent.com/37279233/46704530-2cd2ff00-cc77-11e8-8fa8-d72c0d39fe1b.png">

this is for "based on document with 2 author" file

**Comment by Gurusha95** [comment]
Bug was caused by buffered reader because it was giving garbage values, so it's been changed back to pdfstripper, like before.
