### ISSUE TITLE
Venn diagram Issues

### ISSUE THREAD

**Issue by aerospace666** [CongHien/SWE-Atrax#32]
1. Search for an empty keyword:
    Actual: a list of documents
    Expected: Empty 
    
![venn_empty_keyword_search](https://user-images.githubusercontent.com/20936731/46933012-027da900-d09e-11e8-9f1e-898109d2867c.PNG)

2. Rating in library UI not reflect on the result documents generated in Venn diagram

![venn_rating_library](https://user-images.githubusercontent.com/20936731/46933131-7a4bd380-d09e-11e8-8285-7be8be0ec5a2.PNG)

![venn_rating_in_venn](https://user-images.githubusercontent.com/20936731/46933139-8172e180-d09e-11e8-92b7-fe490cc654a3.PNG)

3. Could not open PDF file to read from the Venn diagram

**Comment by Gurusha95** [comment]
First issue is related to database, not venn.
Second issue - the idea behind developing venn was not this.
Third issue will be fixed

**Comment by aerospace666** [comment]
First issue, empty keyword handler added ( Resolved)

**Comment by CongHien** [comment]
fixed
